target = "https://www.rfc-editor.org/rfc/rfc9114#section-3.3"

[[exception]]
quote = '''
Once a connection to a server endpoint exists, this connection MAY be
reused for requests with multiple different URI authority components.
'''
reason = '''
h3 does not have to do anything specific, as we cannot anticipate when will the client decide to reuse a connection.
'''

[[exception]]
quote = '''
To use an existing connection for a new origin, clients MUST validate
the certificate presented by the server for the new origin server
using the process described in Section 4.3.4 of [HTTP].
'''
reason = '''
h3 does not inspect the certificate messages, so this will have to be enforced by the high-level implementation.
'''

[[exception]]
quote = '''
If the certificate is not acceptable with regard to the new origin
for any reason, the connection MUST NOT be reused and a new
connection SHOULD be established for the new origin.
'''
reason = '''
The requirement applies to the high-level implementation.
'''

[[exception]]
quote = '''
If the reason
the certificate cannot be verified might apply to other origins
already associated with the connection, the client SHOULD revalidate
the server certificate for those origins.
'''
reason = '''
The requirement applies to the high-level implementation.
'''

[[exception]]
quote = '''
A client MAY open
multiple HTTP/3 connections to the same IP address and UDP port using
different transport or TLS configurations but SHOULD avoid creating
multiple connections with the same configuration.
'''
reason = '''
The requirement applies to the high-level implementation.
'''
