target = "https://www.rfc-editor.org/rfc/rfc9114#section-5.1"

[[exception]]
quote = '''
A gateway MAY
maintain connections in anticipation of need rather than incur the
latency cost of connection establishment to servers.
'''
reason = '''
The requirement applies to API gateways.
'''
