target = "https://www.rfc-editor.org/rfc/rfc9114#section-4.2"

[[TODO]]
quote = '''
A request or
response containing uppercase characters in field names MUST be
treated as malformed.
'''

[[TODO]]
quote = '''
The only exception to this is the TE header field, which MAY be
present in an HTTP/3 request header; when it is, it MUST NOT contain
any value other than "trailers".
'''
